<?php
	// Czech page layout
	$ttable = array(
		'book_online' => 'Rezervovat nyní',
		'more_information' => 'Kontaktní informace',
		'weather_info' => 'Počasí',
		'phone' => 'Telefon',
		'mobile_phone' => 'Mobil',
		'mail'=>'Email',
		'name'=>'Jméno',
		'your_message'=>'Vaše zpráva',
		'rooms'=> 'Pokoje',
		'guests'=> 'Osob',
		'parking' => 'Parkovaní na uzamčením dvoře',
		'breakfast'=>'Snídaně',
		'room_guests' => 'Počet hostů',
		'single_beds_count' => 'Jednolůžko',
		'double_beds_count' => 'Dvojlůžko',
		'special_offers' => 'Speciální nabídka',
		'booking_detail' => 'Detaily rezervace',
		'check_in_date' => 'Datum příjezdu',
		'check_out_date' => 'Datum odjezdu',
		'transfer_from_airport' => 'Převoz z letiště',
		'arrival_time' => 'Čas příjezdu',
		'first_room_properties' => 'První pokoj',
		'second_room_properties' => 'Druhý pokoj',
		'third_room_properties' => 'Třetí pokoj',
		'approx_price' => 'Vaše předběžná cena <span class="calculator"> 0 Kč </span>',
		'exchange_rates' => 'Převodní kurz',
      'coupon' => 'Slevový kód',
		'submit' => 'Odeslat',
		'calculate' => 'Spočítat',
      'visited' => 'První návštěva'
	);
?>